; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
;board = dfrobot_firebeetle2_esp32s3
platform = espressif32@5.3.0

[env:dfrobot_firebeetle2_esp32s3]
;platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = dfrobot_firebeetle2_esp32s3
framework = arduino
monitor_speed = 115200
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.extra_flags = 
	-DBOARD_HAS_PSRAM
lib_deps = 
	dfrobot/DFRobot_GDL@^1.0.4
	adafruit/Adafruit seesaw Library@^1.7.9
	crankyoldgit/IRremoteESP8266@^2.9.0
	adafruit/Adafruit Unified Sensor@^1.1.15
	adafruit/Adafruit ADXL343@^1.6.4
	lvgl/lvgl@^8.3.11
	bodmer/TFT_eSPI@^2.5.43
	ulptool-pio
custom_sdkconfig = 
    CONFIG_ESP32S3_ULP_COPROC_ENABLED=y
	CONFIG_ESP32S3_ULP_COPROC_RISCV=y
	CONFIG_ESP32S3_ULP_COPROC_RESERVE_MEM=4096
	CONFIG_ULP_COPROC_ENABLED=y
	CONFIG_ULP_COPROC_RESERVE_MEM=4096
	CONFIG_ULP_COPROC_TYPE_RISCV=y
extra_scripts = 
	pre:/$PROJECT_LIBDEPS_DIR/$PIOENV/ulptool-pio/pre_extra_script_ulptool.py
	post:/$PROJECT_LIBDEPS_DIR/$PIOENV/ulptool-pio/post_extra_script_ulptool.py
build_flags = 
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DARDUINO_USB_MODE=1
platform_packages = platformio/toolchain-esp32s2ulp@^1.22851.191205
