; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
board = dfrobot_firebeetle2_esp32s3

[env:dfrobot_firebeetle2_esp32s3_16MB]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
framework = arduino
monitor_speed = 115200
lib_deps = 
	dfrobot/DFRobot_GDL@^1.0.4
	adafruit/Adafruit seesaw Library@^1.7.9
	crankyoldgit/IRremoteESP8266@^2.9.0
	adafruit/Adafruit Unified Sensor@^1.1.15
	adafruit/Adafruit ADXL343@^1.6.4
build_flags = 
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DARDUINO_USB_MODE=1
