// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: ESPRemote-ui

#ifndef _ESPREMOTE_UI_UI_H
#define _ESPREMOTE_UI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"

///////////////////// SCREENS ////////////////////
#include "ui_Home.h"
#include "ui_Menu.h"
#include "ui_Stats.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_wifi_h_png);   // assets/wifi_H.png

// FONTS
LV_FONT_DECLARE( ui_font_SFRound_20);
LV_FONT_DECLARE( ui_font_SFRound_16);
LV_FONT_DECLARE( ui_font_SFRound_BOLD_16);
LV_FONT_DECLARE( ui_font_SFRound_BOLD_20);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
