// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: ESPRemote-ui

#ifndef UI_HOME_H
#define UI_HOME_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Home
extern void ui_Home_screen_init(void);
extern void ui_Home_screen_destroy(void);
extern lv_obj_t *ui_Home;
extern lv_obj_t *ui_topBar;
extern lv_obj_t *ui_wifiContainer;
extern lv_obj_t *ui_Image1;
extern lv_obj_t *ui_timeContainer;
extern lv_obj_t *ui_Time;
extern lv_obj_t *ui_battContainer;
extern lv_obj_t *ui_Battery;
extern lv_obj_t *ui_Remotes;
extern lv_obj_t *ui_LightTab;
extern lv_obj_t *ui_keypadLegend;
extern lv_obj_t *ui_Container3;
extern lv_obj_t *ui_Container4;
extern lv_obj_t *ui_Container5;
extern lv_obj_t *ui_Container6;
extern lv_obj_t *ui_AVTab;
extern lv_obj_t *ui_FanTab;
extern lv_obj_t *ui_fanPowerBtn;
extern lv_obj_t *ui_Label3;
extern lv_obj_t *ui_fanUpBtn;
extern lv_obj_t *ui_Label4;
extern lv_obj_t *ui_fanDownBtn;
extern lv_obj_t *ui_Label5;
extern lv_obj_t *ui_fanModeBtn;
extern lv_obj_t *ui_Label6;
extern lv_obj_t *ui_fanMuteBtn;
extern lv_obj_t *ui_Label7;
extern lv_obj_t *ui_fanOscBtn;
extern lv_obj_t *ui_Label8;
extern lv_obj_t *ui_fanTimerBtn;
extern lv_obj_t *ui_Label9;
extern lv_obj_t *ui_CandleTab;
extern lv_obj_t *ui_TabPage5;
extern lv_obj_t *ui_Error_Box;
extern lv_obj_t *ui_Container7;
extern lv_obj_t *ui_Container8;
extern void ui_event_menuBtn( lv_event_t * e);
extern lv_obj_t *ui_menuBtn;
extern lv_obj_t *ui_hamburgerMenuLabel;
extern lv_obj_t *ui_topBun;
extern lv_obj_t *ui_burger;
extern lv_obj_t *ui_bottomBun;
extern lv_obj_t *ui_menuBtnLabel;
extern lv_obj_t *ui_Container9;
extern lv_obj_t *ui_Container10;
extern void ui_event_slpBtn( lv_event_t * e);
extern lv_obj_t *ui_slpBtn;
extern lv_obj_t *ui_Label1;
// CUSTOM VARIABLES
extern lv_obj_t *uic_Error_Box;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

