// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: ESPRemote-ui

#include "ui.h"

lv_obj_t *uic_Error_Box;
lv_obj_t *ui_Home = NULL;lv_obj_t *ui_topBar = NULL;lv_obj_t *ui_wifiContainer = NULL;lv_obj_t *ui_Image1 = NULL;lv_obj_t *ui_timeContainer = NULL;lv_obj_t *ui_Time = NULL;lv_obj_t *ui_battContainer = NULL;lv_obj_t *ui_Battery = NULL;lv_obj_t *ui_Remotes = NULL;lv_obj_t *ui_LightTab = NULL;lv_obj_t *ui_keypadLegend = NULL;lv_obj_t *ui_Container3 = NULL;lv_obj_t *ui_Container4 = NULL;lv_obj_t *ui_Container5 = NULL;lv_obj_t *ui_Container6 = NULL;lv_obj_t *ui_AVTab = NULL;lv_obj_t *ui_FanTab = NULL;lv_obj_t *ui_fanPowerBtn = NULL;lv_obj_t *ui_Label3 = NULL;lv_obj_t *ui_fanUpBtn = NULL;lv_obj_t *ui_Label4 = NULL;lv_obj_t *ui_fanDownBtn = NULL;lv_obj_t *ui_Label5 = NULL;lv_obj_t *ui_fanModeBtn = NULL;lv_obj_t *ui_Label6 = NULL;lv_obj_t *ui_fanMuteBtn = NULL;lv_obj_t *ui_Label7 = NULL;lv_obj_t *ui_fanOscBtn = NULL;lv_obj_t *ui_Label8 = NULL;lv_obj_t *ui_fanTimerBtn = NULL;lv_obj_t *ui_Label9 = NULL;lv_obj_t *ui_CandleTab = NULL;lv_obj_t *ui_TabPage5 = NULL;lv_obj_t *ui_Error_Box = NULL;lv_obj_t *ui_Container7 = NULL;lv_obj_t *ui_Container8 = NULL;lv_obj_t *ui_menuBtn = NULL;lv_obj_t *ui_hamburgerMenuLabel = NULL;lv_obj_t *ui_topBun = NULL;lv_obj_t *ui_burger = NULL;lv_obj_t *ui_bottomBun = NULL;lv_obj_t *ui_menuBtnLabel = NULL;lv_obj_t *ui_Container9 = NULL;lv_obj_t *ui_Container10 = NULL;lv_obj_t *ui_slpBtn = NULL;lv_obj_t *ui_Label1 = NULL;
// event funtions
void ui_event_menuBtn( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Menu, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Menu_screen_init);
}
}

void ui_event_slpBtn( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Menu, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Menu_screen_init);
}
}

// build funtions

void ui_Home_screen_init(void)
{
ui_Home = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Home, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Home, lv_color_hex(0x56749D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Home, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_topBar = lv_obj_create(ui_Home);
lv_obj_remove_style_all(ui_topBar);
lv_obj_set_width( ui_topBar, 320);
lv_obj_set_height( ui_topBar, 34);
lv_obj_set_align( ui_topBar, LV_ALIGN_TOP_MID );
lv_obj_set_flex_flow(ui_topBar,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_topBar, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_topBar, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_topBar, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_topBar, 45, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_topBar, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_topBar, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_topBar, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_topBar, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_topBar, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_topBar, 50, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_topBar, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_topBar, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_topBar, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_topBar, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_topBar, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_topBar, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_wifiContainer = lv_obj_create(ui_topBar);
lv_obj_remove_style_all(ui_wifiContainer);
lv_obj_set_width( ui_wifiContainer, 100);
lv_obj_set_height( ui_wifiContainer, 50);
lv_obj_set_align( ui_wifiContainer, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_wifiContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image1 = lv_img_create(ui_wifiContainer);
lv_img_set_src(ui_Image1, &ui_img_wifi_h_png);
lv_obj_set_width( ui_Image1, 26);
lv_obj_set_height( ui_Image1, 20);
lv_obj_set_align( ui_Image1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image1, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_clear_flag( ui_Image1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Image1,104);
lv_obj_set_style_pad_left(ui_Image1, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Image1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Image1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Image1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_timeContainer = lv_obj_create(ui_topBar);
lv_obj_remove_style_all(ui_timeContainer);
lv_obj_set_width( ui_timeContainer, 100);
lv_obj_set_height( ui_timeContainer, 50);
lv_obj_set_align( ui_timeContainer, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_timeContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Time = lv_label_create(ui_timeContainer);
lv_obj_set_width( ui_Time, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Time, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Time, LV_ALIGN_CENTER );
lv_label_set_text(ui_Time,"10:30 AM");
lv_obj_set_style_text_color(ui_Time, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Time, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Time, &ui_font_SFRound_BOLD_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_battContainer = lv_obj_create(ui_topBar);
lv_obj_remove_style_all(ui_battContainer);
lv_obj_set_width( ui_battContainer, 100);
lv_obj_set_height( ui_battContainer, 50);
lv_obj_set_align( ui_battContainer, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_battContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Battery = lv_bar_create(ui_battContainer);
lv_bar_set_value(ui_Battery,25,LV_ANIM_OFF);
lv_bar_set_start_value(ui_Battery, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_Battery, 47);
lv_obj_set_height( ui_Battery, 10);
lv_obj_set_align( ui_Battery, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_Battery, lv_color_hex(0x505050), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Battery, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_Battery, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Battery, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_Remotes = lv_tabview_create(ui_Home, LV_DIR_TOP, 30);
lv_obj_set_width( ui_Remotes, 310);
lv_obj_set_height( ui_Remotes, 380);
lv_obj_set_x( ui_Remotes, 0 );
lv_obj_set_y( ui_Remotes, -5 );
lv_obj_set_align( ui_Remotes, LV_ALIGN_BOTTOM_MID );
lv_obj_clear_flag( ui_Remotes, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Remotes, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Remotes, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Remotes, 25, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_text_font(lv_tabview_get_tab_btns(ui_Remotes), &ui_font_SFRound_16,  LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(lv_tabview_get_tab_btns(ui_Remotes), 8,  LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_radius(lv_tabview_get_tab_btns(ui_Remotes), 8,  LV_PART_ITEMS| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(lv_tabview_get_tab_btns(ui_Remotes), lv_color_hex(0xFFFFFF),  LV_PART_ITEMS | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(lv_tabview_get_tab_btns(ui_Remotes), 255,  LV_PART_ITEMS| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(lv_tabview_get_tab_btns(ui_Remotes), lv_color_hex(0xFFFFFF),  LV_PART_ITEMS | LV_STATE_CHECKED );
lv_obj_set_style_text_opa(lv_tabview_get_tab_btns(ui_Remotes), 255,  LV_PART_ITEMS| LV_STATE_CHECKED);
lv_obj_set_style_text_font(lv_tabview_get_tab_btns(ui_Remotes), &ui_font_SFRound_16,  LV_PART_ITEMS| LV_STATE_CHECKED);
lv_obj_set_style_bg_color(lv_tabview_get_tab_btns(ui_Remotes), lv_color_hex(0x79BAEC),  LV_PART_ITEMS | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(lv_tabview_get_tab_btns(ui_Remotes), 255,  LV_PART_ITEMS| LV_STATE_CHECKED);
lv_obj_set_style_border_side(lv_tabview_get_tab_btns(ui_Remotes), LV_BORDER_SIDE_NONE,  LV_PART_ITEMS| LV_STATE_CHECKED);

ui_LightTab = lv_tabview_add_tab(ui_Remotes, "Lights");
lv_obj_clear_flag( ui_LightTab, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_set_style_bg_color(ui_LightTab, lv_color_hex(0x2E0B0B), LV_PART_SCROLLBAR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_LightTab, 255, LV_PART_SCROLLBAR| LV_STATE_DEFAULT);

ui_keypadLegend = lv_obj_create(ui_LightTab);
lv_obj_remove_style_all(ui_keypadLegend);
lv_obj_set_width( ui_keypadLegend, 304);
lv_obj_set_height( ui_keypadLegend, 35);
lv_obj_set_align( ui_keypadLegend, LV_ALIGN_BOTTOM_MID );
lv_obj_set_flex_flow(ui_keypadLegend,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_keypadLegend, LV_FLEX_ALIGN_SPACE_EVENLY, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_keypadLegend, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Container3 = lv_obj_create(ui_keypadLegend);
lv_obj_remove_style_all(ui_Container3);
lv_obj_set_width( ui_Container3, 80);
lv_obj_set_height( ui_Container3, 50);
lv_obj_set_align( ui_Container3, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_Container3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Container3, 50, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Container3, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_Container3, LV_BORDER_SIDE_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container4 = lv_obj_create(ui_keypadLegend);
lv_obj_remove_style_all(ui_Container4);
lv_obj_set_width( ui_Container4, 80);
lv_obj_set_height( ui_Container4, 50);
lv_obj_set_align( ui_Container4, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Container4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_Container4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Container4, 50, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Container4, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_Container4, LV_BORDER_SIDE_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container5 = lv_obj_create(ui_keypadLegend);
lv_obj_remove_style_all(ui_Container5);
lv_obj_set_width( ui_Container5, 80);
lv_obj_set_height( ui_Container5, 50);
lv_obj_set_align( ui_Container5, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Container5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_Container5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Container5, 50, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Container5, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_Container5, LV_BORDER_SIDE_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container6 = lv_obj_create(ui_keypadLegend);
lv_obj_remove_style_all(ui_Container6);
lv_obj_set_width( ui_Container6, 80);
lv_obj_set_height( ui_Container6, 50);
lv_obj_set_align( ui_Container6, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Container6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_AVTab = lv_tabview_add_tab(ui_Remotes, "A / V");

ui_FanTab = lv_tabview_add_tab(ui_Remotes, "Fan");

ui_fanPowerBtn = lv_btn_create(ui_FanTab);
lv_obj_set_width( ui_fanPowerBtn, 100);
lv_obj_set_height( ui_fanPowerBtn, 50);
lv_obj_set_x( ui_fanPowerBtn, -91 );
lv_obj_set_y( ui_fanPowerBtn, -134 );
lv_obj_set_align( ui_fanPowerBtn, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_fanPowerBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_fanPowerBtn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label3 = lv_label_create(ui_fanPowerBtn);
lv_obj_set_width( ui_Label3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label3, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label3,"Power");
lv_obj_set_style_text_font(ui_Label3, &ui_font_SFRound_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_fanUpBtn = lv_btn_create(ui_FanTab);
lv_obj_set_width( ui_fanUpBtn, 100);
lv_obj_set_height( ui_fanUpBtn, 50);
lv_obj_set_x( ui_fanUpBtn, 86 );
lv_obj_set_y( ui_fanUpBtn, -129 );
lv_obj_set_align( ui_fanUpBtn, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_fanUpBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_fanUpBtn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label4 = lv_label_create(ui_fanUpBtn);
lv_obj_set_width( ui_Label4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label4, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label4,"up");
lv_obj_set_style_text_font(ui_Label4, &ui_font_SFRound_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_fanDownBtn = lv_btn_create(ui_FanTab);
lv_obj_set_width( ui_fanDownBtn, 100);
lv_obj_set_height( ui_fanDownBtn, 50);
lv_obj_set_x( ui_fanDownBtn, 86 );
lv_obj_set_y( ui_fanDownBtn, -62 );
lv_obj_set_align( ui_fanDownBtn, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_fanDownBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_fanDownBtn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label5 = lv_label_create(ui_fanDownBtn);
lv_obj_set_width( ui_Label5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label5, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label5,"dn");

ui_fanModeBtn = lv_btn_create(ui_FanTab);
lv_obj_set_width( ui_fanModeBtn, 100);
lv_obj_set_height( ui_fanModeBtn, 50);
lv_obj_set_x( ui_fanModeBtn, -92 );
lv_obj_set_y( ui_fanModeBtn, -72 );
lv_obj_set_align( ui_fanModeBtn, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_fanModeBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_fanModeBtn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label6 = lv_label_create(ui_fanModeBtn);
lv_obj_set_width( ui_Label6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label6, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label6,"Mode");
lv_obj_set_style_text_font(ui_Label6, &ui_font_SFRound_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_fanMuteBtn = lv_btn_create(ui_FanTab);
lv_obj_set_width( ui_fanMuteBtn, 100);
lv_obj_set_height( ui_fanMuteBtn, 50);
lv_obj_set_x( ui_fanMuteBtn, -88 );
lv_obj_set_y( ui_fanMuteBtn, 75 );
lv_obj_set_align( ui_fanMuteBtn, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_fanMuteBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_fanMuteBtn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label7 = lv_label_create(ui_fanMuteBtn);
lv_obj_set_width( ui_Label7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label7, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label7,"Mute");
lv_obj_set_style_text_font(ui_Label7, &ui_font_SFRound_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_fanOscBtn = lv_btn_create(ui_FanTab);
lv_obj_set_width( ui_fanOscBtn, 100);
lv_obj_set_height( ui_fanOscBtn, 50);
lv_obj_set_x( ui_fanOscBtn, -5 );
lv_obj_set_y( ui_fanOscBtn, -7 );
lv_obj_set_align( ui_fanOscBtn, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_fanOscBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_fanOscBtn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label8 = lv_label_create(ui_fanOscBtn);
lv_obj_set_width( ui_Label8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label8, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label8, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label8,"Oscillate");

ui_fanTimerBtn = lv_btn_create(ui_FanTab);
lv_obj_set_width( ui_fanTimerBtn, 100);
lv_obj_set_height( ui_fanTimerBtn, 50);
lv_obj_set_x( ui_fanTimerBtn, 82 );
lv_obj_set_y( ui_fanTimerBtn, 64 );
lv_obj_set_align( ui_fanTimerBtn, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_fanTimerBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_fanTimerBtn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label9 = lv_label_create(ui_fanTimerBtn);
lv_obj_set_width( ui_Label9, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label9, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label9, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label9,"Sleep Timer");

ui_CandleTab = lv_tabview_add_tab(ui_Remotes, "Candle");

ui_TabPage5 = lv_tabview_add_tab(ui_Remotes, "Title 5");

ui_Error_Box = lv_obj_create(ui_Home);
lv_obj_set_width( ui_Error_Box, 100);
lv_obj_set_height( ui_Error_Box, 50);
lv_obj_set_align( ui_Error_Box, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Error_Box, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_Error_Box, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Container7 = lv_obj_create(ui_Home);
lv_obj_remove_style_all(ui_Container7);
lv_obj_set_width( ui_Container7, 320);
lv_obj_set_height( ui_Container7, 50);
lv_obj_set_x( ui_Container7, 0 );
lv_obj_set_y( ui_Container7, -175 );
lv_obj_set_align( ui_Container7, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container7,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Container7, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Container7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Container8 = lv_obj_create(ui_Container7);
lv_obj_remove_style_all(ui_Container8);
lv_obj_set_width( ui_Container8, 100);
lv_obj_set_height( ui_Container8, 50);
lv_obj_set_align( ui_Container8, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Container8, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_menuBtn = lv_btn_create(ui_Container8);
lv_obj_set_width( ui_menuBtn, 71);
lv_obj_set_height( ui_menuBtn, 35);
lv_obj_set_align( ui_menuBtn, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_menuBtn,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_menuBtn, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_menuBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_menuBtn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_menuBtn, 8, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_hamburgerMenuLabel = lv_obj_create(ui_menuBtn);
lv_obj_remove_style_all(ui_hamburgerMenuLabel);
lv_obj_set_width( ui_hamburgerMenuLabel, 10);
lv_obj_set_height( ui_hamburgerMenuLabel, 15);
lv_obj_set_align( ui_hamburgerMenuLabel, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_hamburgerMenuLabel,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_hamburgerMenuLabel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_hamburgerMenuLabel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_topBun = lv_obj_create(ui_hamburgerMenuLabel);
lv_obj_remove_style_all(ui_topBun);
lv_obj_set_width( ui_topBun, 10);
lv_obj_set_height( ui_topBun, 5);
lv_obj_set_align( ui_topBun, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_topBun, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_topBun, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_topBun, 150, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_topBun, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_topBun, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_burger = lv_obj_create(ui_hamburgerMenuLabel);
lv_obj_remove_style_all(ui_burger);
lv_obj_set_width( ui_burger, 10);
lv_obj_set_height( ui_burger, 5);
lv_obj_set_align( ui_burger, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_burger, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_burger, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_burger, 150, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_burger, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_burger, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_bottomBun = lv_obj_create(ui_hamburgerMenuLabel);
lv_obj_remove_style_all(ui_bottomBun);
lv_obj_set_width( ui_bottomBun, 10);
lv_obj_set_height( ui_bottomBun, 5);
lv_obj_set_align( ui_bottomBun, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_bottomBun, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_bottomBun, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_bottomBun, 150, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_bottomBun, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_bottomBun, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_menuBtnLabel = lv_label_create(ui_menuBtn);
lv_obj_set_width( ui_menuBtnLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_menuBtnLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_menuBtnLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_menuBtnLabel,"Menu");
lv_obj_set_style_text_font(ui_menuBtnLabel, &ui_font_SFRound_BOLD_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container9 = lv_obj_create(ui_Container7);
lv_obj_remove_style_all(ui_Container9);
lv_obj_set_width( ui_Container9, 100);
lv_obj_set_height( ui_Container9, 50);
lv_obj_set_align( ui_Container9, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Container9, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Container10 = lv_obj_create(ui_Container7);
lv_obj_remove_style_all(ui_Container10);
lv_obj_set_width( ui_Container10, 100);
lv_obj_set_height( ui_Container10, 50);
lv_obj_set_align( ui_Container10, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Container10, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_slpBtn = lv_btn_create(ui_Container10);
lv_obj_set_width( ui_slpBtn, 50);
lv_obj_set_height( ui_slpBtn, 30);
lv_obj_set_align( ui_slpBtn, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_slpBtn,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_slpBtn, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_slpBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_slpBtn, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_slpBtn, 8, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label1 = lv_label_create(ui_slpBtn);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"Sleep");

lv_obj_add_event_cb(ui_menuBtn, ui_event_menuBtn, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_slpBtn, ui_event_slpBtn, LV_EVENT_ALL, NULL);
uic_Error_Box = ui_Error_Box;

}

void ui_Home_screen_destroy(void)
{
   if (ui_Home) lv_obj_del(ui_Home);

// NULL screen variables
ui_Home= NULL;
ui_topBar= NULL;
ui_wifiContainer= NULL;
ui_Image1= NULL;
ui_timeContainer= NULL;
ui_Time= NULL;
ui_battContainer= NULL;
ui_Battery= NULL;
ui_Remotes= NULL;
ui_LightTab= NULL;
ui_keypadLegend= NULL;
ui_Container3= NULL;
ui_Container4= NULL;
ui_Container5= NULL;
ui_Container6= NULL;
ui_AVTab= NULL;
ui_FanTab= NULL;
ui_fanPowerBtn= NULL;
ui_Label3= NULL;
ui_fanUpBtn= NULL;
ui_Label4= NULL;
ui_fanDownBtn= NULL;
ui_Label5= NULL;
ui_fanModeBtn= NULL;
ui_Label6= NULL;
ui_fanMuteBtn= NULL;
ui_Label7= NULL;
ui_fanOscBtn= NULL;
ui_Label8= NULL;
ui_fanTimerBtn= NULL;
ui_Label9= NULL;
ui_CandleTab= NULL;
ui_TabPage5= NULL;
uic_Error_Box= NULL;
ui_Error_Box= NULL;
ui_Container7= NULL;
ui_Container8= NULL;
ui_menuBtn= NULL;
ui_hamburgerMenuLabel= NULL;
ui_topBun= NULL;
ui_burger= NULL;
ui_bottomBun= NULL;
ui_menuBtnLabel= NULL;
ui_Container9= NULL;
ui_Container10= NULL;
ui_slpBtn= NULL;
ui_Label1= NULL;

}
