// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t *ui_Screen1 = NULL;lv_obj_t *ui_Container1 = NULL;lv_obj_t *ui_Image1 = NULL;lv_obj_t *ui_Time = NULL;lv_obj_t *ui_Battery = NULL;lv_obj_t *ui_TabView1 = NULL;lv_obj_t *ui_TabPage1 = NULL;lv_obj_t *ui_TabPage2 = NULL;lv_obj_t *ui_TabPage3 = NULL;lv_obj_t *ui_Button2 = NULL;lv_obj_t *ui_Label2 = NULL;
// event funtions
void ui_event_Button2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_screen_change( &ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen2_screen_init);
}
}

// build funtions

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_remove_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x56749D), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container1 = lv_obj_create(ui_Screen1);
lv_obj_remove_style_all(ui_Container1);
lv_obj_set_width( ui_Container1, 320);
lv_obj_set_height( ui_Container1, 34);
lv_obj_set_align( ui_Container1, LV_ALIGN_TOP_MID );
lv_obj_set_flex_flow(ui_Container1,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Container1, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
lv_obj_remove_flag( ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Container1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Container1, 30, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Container1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Container1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_Container1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_Container1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_Container1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_Container1, 50, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_Container1, 20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_Container1, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Container1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Container1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Container1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Container1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image1 = lv_image_create(ui_Container1);
lv_image_set_src(ui_Image1, &ui_img_wifi_h_png);
lv_obj_set_width( ui_Image1, 26);
lv_obj_set_height( ui_Image1, 20);
lv_obj_set_x( ui_Image1, -29 );
lv_obj_set_y( ui_Image1, -42 );
lv_obj_set_align( ui_Image1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image1, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_Image1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_image_set_scale(ui_Image1,104);
lv_image_set_inner_align( ui_Image1, LV_IMAGE_ALIGN_STRETCH );
lv_obj_set_style_pad_left(ui_Image1, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Image1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Image1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Image1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Time = lv_label_create(ui_Container1);
lv_obj_set_width( ui_Time, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Time, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Time, -4 );
lv_obj_set_y( ui_Time, -227 );
lv_obj_set_align( ui_Time, LV_ALIGN_CENTER );
lv_label_set_text(ui_Time,"10:30 AM");
lv_obj_set_style_text_color(ui_Time, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Time, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Battery = lv_bar_create(ui_Container1);
lv_bar_set_value(ui_Battery,25,LV_ANIM_OFF);
lv_bar_set_start_value(ui_Battery, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_Battery, 47);
lv_obj_set_height( ui_Battery, 10);
lv_obj_set_x( ui_Battery, 103 );
lv_obj_set_y( ui_Battery, -225 );
lv_obj_set_align( ui_Battery, LV_ALIGN_CENTER );
lv_obj_set_style_bg_color(ui_Battery, lv_color_hex(0x505050), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Battery, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_bg_color(ui_Battery, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Battery, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

//Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
if (lv_obj_get_style_pad_top(ui_Battery,LV_PART_MAIN) > 0) lv_obj_set_style_pad_right( ui_Battery, lv_obj_get_style_pad_right(ui_Battery,LV_PART_MAIN) + 1, LV_PART_MAIN );
ui_TabView1 = lv_tabview_create(ui_Screen1);
lv_tabview_set_tab_bar_position(ui_TabView1,LV_DIR_BOTTOM);
lv_tabview_set_tab_bar_size(ui_TabView1,25);
lv_obj_set_width( ui_TabView1, 291);
lv_obj_set_height( ui_TabView1, 380);
lv_obj_set_x( ui_TabView1, -2 );
lv_obj_set_y( ui_TabView1, 104 );
lv_obj_set_align( ui_TabView1, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_TabView1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_TabPage1 = lv_tabview_add_tab(ui_TabView1, "Title 1");

ui_TabPage2 = lv_tabview_add_tab(ui_TabView1, "Title 2");

ui_TabPage3 = lv_tabview_add_tab(ui_TabView1, "Title 3");

ui_Button2 = lv_button_create(ui_Screen1);
lv_obj_set_width( ui_Button2, 100);
lv_obj_set_height( ui_Button2, 25);
lv_obj_set_x( ui_Button2, -94 );
lv_obj_set_y( ui_Button2, -177 );
lv_obj_set_align( ui_Button2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_remove_flag( ui_Button2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label2 = lv_label_create(ui_Button2);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label2,"Menu");

lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);

}

void ui_Screen1_screen_destroy(void)
{
   if (ui_Screen1) lv_obj_del(ui_Screen1);

// NULL screen variables
ui_Screen1= NULL;
ui_Container1= NULL;
ui_Image1= NULL;
ui_Time= NULL;
ui_Battery= NULL;
ui_TabView1= NULL;
ui_TabPage1= NULL;
ui_TabPage2= NULL;
ui_TabPage3= NULL;
ui_Button2= NULL;
ui_Label2= NULL;

}
