// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: ESPRemote-ui

#ifndef UI_STATS_H
#define UI_STATS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Stats
extern void ui_Stats_screen_init(void);
extern void ui_Stats_screen_destroy(void);
extern lv_obj_t *ui_Stats;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

