// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: ESPRemote-ui

#include "ui.h"

lv_obj_t *ui_Stats = NULL;
// event funtions

// build funtions

void ui_Stats_screen_init(void)
{
ui_Stats = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Stats, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

}

void ui_Stats_screen_destroy(void)
{
   if (ui_Stats) lv_obj_del(ui_Stats);

// NULL screen variables
ui_Stats= NULL;

}
