// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: ESPRemote-ui

#include "ui.h"

const ui_theme_variable_t _ui_theme_color_Blue[2] = {0x000000, 0x000000};
const ui_theme_variable_t _ui_theme_alpha_Blue[2] = {255, 255};
uint8_t ui_theme_idx = UI_THEME_ESP_REMOTE;

void ui_theme_set(uint8_t theme_idx)
{
    ui_theme_idx = theme_idx;
    _ui_theme_set_variable_styles(UI_VARIABLE_STYLES_MODE_FOLLOW);
}

